oddnumber=[1,3,5,7,9]
evennumber=[2,6,8,10]
oddnumber.append(11)
print(oddnumber)
evennumber.insert(2,4)
print(evennumber)
oddandeven=oddnumber+evennumber
print(oddandeven)
oddnumber.append(2.4)
print(oddnumber)
oddnumber.remove(2.4)
print(oddnumber)
evennumber.insert(3,4)
print(evennumber)
poppedeve=evennumber.pop(3)
print(poppedeve)
sls=oddnumber[1:4]
print(sls)
print(evennumber[4])